### ISSUE TITLE
Database credentials are in the source code

### ISSUE THREAD

**Issue by coffeebrick** [jappe999/project-cards#36]
## Expected Behavior

When I clone the project, I should copy a `.env.example` file to a `.env` file. The `.env` file should be in the `.gitignore` so it is not commited. In the `.env` file I should set the database provider and credentials

## Current Behavior

When I clone the project and try to start it, the following error appears:
```
[Nest] 15011   - 10/03/2019, 10:11 AM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3011ms
error: password authentication failed for user "root"
    at Connection.parseE (/home/jappe/devpot/workspace/cards/project/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/jappe/devpot/workspace/cards/project/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/jappe/devpot/workspace/cards/project/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

This means that without me knowing the database credentials were set. And I don't know where to change it.

## Possible Solution

Create a `.env.example` file with the database provider and credentials. By adding this file and adding a JWT_SECRET issue #34 will also be fixed.

## Steps to Reproduce (for bugs)

1. Build the project with a JWT_SECRET set.

## Context

I cannot build the project if I don't know what to do.

## Your Environment

- Version used: 1.0
- Environment name and version (e.g. Chrome 39, node.js 5.4): NA
- Operating System and version (desktop or mobile): NA

**Comment by coffeebrick** [comment]
This is also an issue for the production version, because those credentials are in there as well. :(
